@startuml
left to right direction
actor 系统管理员
usecase 管理用户
usecase 管理机房可用时间段
usecase 设置学时
usecase 统计上机情况
usecase 登录日志



系统管理员 -->管理用户
usecase 查询用户
usecase 新增用户
usecase 注销或删除用户
管理用户 -->查询用户
管理用户 -->新增用户
管理用户 -->注销或删除用户

系统管理员 -->管理机房可用时间段
usecase 设置开放时间段
usecase 添加不可用时间段
管理机房可用时间段 -->设置开放时间段
管理机房可用时间段 -->添加不可用时间段

系统管理员 -->设置学时
usecase 查询班级学时信息
usecase 编辑或删除班级学时信息
usecase 新增班级学时信息
设置学时 -->查询班级学时信息
设置学时 -->编辑或删除班级学时信息
设置学时 -->新增班级学时信息


系统管理员 -->统计上机情况
usecase 查询上机记录
usecase 查看上机统计
统计上机情况 -->查询上机记录
统计上机情况 -->查看上机统计

系统管理员 -->登录日志
usecase 查询登录日志
usecase 记录登录日志
登录日志 -->查询登录日志
登录日志 -->记录登录日志

@enduml
