'系统管理员，管理学时

@startuml
start
:登录系统;
if (是否登录成功？) then (是)
  :选择学时管理菜单;
  :显示学时管理菜单;
  :选择操作（新增班级学时/修改班级学时/删除班级学时）;
    if (新增学时间信息？) then (是)
      if (是否批量添加) is (是) then
        :Excel导入;
      else (否)
        :选择班级;
        :输入学时信息;
        :新增班级学时;
      endif
    else if (编辑/删除班级学时信息？) then (是)
      if (需要查询？) is (是) then
        :按班级查询;
      else (否)
      endif
    :选择学时信息;
    :修改或删除;
    endif
else (登录失败)
:显示登录失败消息;
endif
stop
@enduml
