'系统管理员，管理可用时间段

@startuml
start
:登录系统;
if (是否登录成功？) then (是)
  :选择机房管理菜单;
  :显示机房管理菜单;
    if (选择操作？)
      :设置开放时间段;
    else
      :添加不可用时间段;
      if (是否批量设置) is (是) then
        :Excel导入;
      else (否)
        :选择日期;
              :选择不可用时间段;
              :添加不可用时间段;
      endif
    endif
else (登录失败)
  :显示登录失败消息;
endif
stop
@enduml
