'系统管理员，管理用户

@startuml
start
:登录系统;
if (登录成功？) then (是)
    :选择用户管理菜单;
    :显示用户管理菜单;
    :选择操作;
    if (修改或注销用户？) then (是)
        if (需要查询？) is (是) then
          :按条件查询;
          else (否)
        endif
      :选择用户;
      :修改或注销;
    else if (批量导入用户？) then (是)
      :导入用户信息;
    else if (新增用户？) then (是)
      :填写用户信息;
      :创建新用户;
    endif
else (否)
  :显示登录失败消息;
endif
stop
@enduml
