'系统管理员，查看上机统计

@startuml
start
:登录系统;
if (是否登录成功？) then (是)
  :选择上机统计菜单;
  :显示上机统计菜单;
    :选择操作（查看上机记录/查看上课统计）;
    if (查看上机记录？) then (是)
      if (按班、机房、时间查看？) is (是) then
        :输入条件;
      endif
      :显示上机记录;
      if (是否导出？) then (是)
        :导出Excel;
      endif
    else if(查看上机统计？)
      if (按班、机房、时间统计？) is (是) then
        :输入条件;
      endif
      :生成上机统计图表;
    endif
else (登录失败)
  :显示登录失败消息;
endif
stop
@enduml
