@startuml
|学生|
start
:浏览机房;
|系统界面|
:显示机房状态;
|学生|
:去机房;
|机房管理员|
:提出在机房上机;
:查询机房状态;
|系统界面|
:显示机房状态;
|机房管理员|
if (机房可用?) then (是)
  :记录学生使用机房;
  :分配机位;
else (否)
  :拒绝学生请求;
  stop
endif
|学生|
:进入机房;
:使用机位;
:完成使用;
|机房管理员|
:收回机位;
:更新机房使用记录;
|学生|
:离开机房;
stop
@enduml
