'学生，个人统计

@startuml
start
:登录系统;
if (是否登录成功？) then (是)
  :显示学生主页;
  :选择个人统计;
  :显示个人统计;
    :选择操作（查看上机记录/查看上课统计）;
    if (查看上机记录？) then (是)
      :显示上机记录;
    else if(查看上机统计？)
      if (机房、时间统计？) is (是) then
        :输入条件;
      endif
      :生成上机统计图表;
    endif
else (登录失败)
  :显示登录失败消息;
endif
stop
@enduml