'学生，个人上机情况

@startuml
start
:登录系统;
if (是否登录成功？) then (是)
  :显示学生主页;
  :选择个人上机情况;
  :获取个人上机情况;
  if (获取成功？) then (是)
    :显示个人上机情况;
  else (否)
    :显示获取失败消息;
  endif
else (登录失败)
  :显示登录失败消息;
endif
stop
@enduml
